---
- name: Install and configure webserver
  hosts: web01
  become: yes
  vars_files:
   - vars/main.yml  
  tasks:
    - name: Install Httpd on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Display Httpd status
      debug:
        msg: "Httpd server is active and running."
      when: ansible_distribution == "CentOS"

    - name: Remove old script2.sh if it exists
      file:
        path: "{{ web_server_root }}/script2.sh"
        state: absent
      when: ansible_distribution == "CentOS"    

    - name: Remove old styles.css if it exists
      file:
        path: "{{ web_server_root }}/styles.css"
        state: absent
      when: ansible_distribution == "CentOS"

          
    - name: Deploy CGI script using template 
      template:
        # src: ./files/index.html
        src: "{{ script_source }}"
        dest: "{{ script_destination }}"
        owner: root
        group: root
        mode: '0777'
        backup: yes
      when: ansible_distribution == "CentOS"

    - name: Deploy CSS file
      copy:
        src: ./templates/styles.css
        dest: "{{ web_server_root }}/styles.css"
        owner: root
        group: root
        mode: '0777'
      when: ansible_distribution == "CentOS"

    - name: Display Servce Status
      debug:
        msg: "Go to http://<publicIP>/cgi-bin/script2.sh"
      when: ansible_distribution == "CentOS"
